name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start FastAPI server
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 10  # Give the server some time to start
      - name: Run tests
        run: |
          cd app
          pytest