name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "INVESTIDOR10_API_ACOES=${{ secrets.INVESTIDOR10_API_ACOES }}" >> .env
          echo "INVESTIDOR10_API_NETGROWTH=${{ secrets.INVESTIDOR10_API_NETGROWTH }}" >> .env

      - name: Run tests
        run: |
          cd app  # Navigate to the app directory
          pytest